apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | trim | nindent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
  name: {{ template "simplehelm.fullname" . }}
  labels:
    app: {{ template "simplehelm.name" . }}
    chart: {{ template "simplehelm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "simplehelm.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "simplehelm.name" . }}
        release: {{ .Release.Name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: wwwdata-volume
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      volumes:
        - name: wwwdata-volume
          configMap:
            name: {{ template "simplehelm.fullname" . }}
